# Copyright (C) 2026 AnkiCraft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <https://www.gnu.org/licenses/>.

from __future__ import annotations

from functools import lru_cache

from .effects import is_celebration_milestone

FALLBACK: str = "en"

TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {"streak": "{count} in a row", "opt_theme": "Color theme", "opt_effects": "Streak effects (aura/gold/text)", "opt_save": "OK", "opt_cancel": "Cancel", "opt_defaults": "Restore defaults", "theme_classic_green": "Classic green", "theme_fire_red": "Fire red", "theme_lagoon_turquoise": "Lagoon turquoise", "theme_ocean_blue": "Ocean blue", "theme_rose_pink": "Rose pink", "theme_royal_purple": "Royal purple", "theme_sunset_orange": "Sunset orange", "opt_push": "Top spacing (px)", "version_line": "{name} v{version}", "welcome_title": "{name} v{version}", "kofi_button": "☕ Buy me a coffee", "kofi_tooltip": "Support development on Ko-fi", "patreon_button": "♥ Patreon", "rate_button": "👍 Rate this add-on", "report_button": "Report a bug", "welcome_close": "Close", "welcome_body": "{name} adds an animated progress bar at the top of the reviewer, showing how far you are through your session, with optional streak effects. You can change the color theme and other options anytime from Tools → Add-ons → {name} → Config.", "welcome_support_note": "This add-on is free and open source (AGPLv3). If it's useful to you, consider supporting its development below.",},
    "es": {"streak": "{count} seguidas", "opt_theme": "Tema de color", "opt_effects": "Efectos de racha (aura/oro/texto)", "opt_save": "Aceptar", "opt_cancel": "Cancelar", "opt_defaults": "Restaurar los valores predeterminados", "theme_classic_green": "Verde clásico", "theme_fire_red": "Rojo fuego", "theme_lagoon_turquoise": "Turquesa laguna", "theme_ocean_blue": "Azul océano", "theme_rose_pink": "Rosa suave", "theme_royal_purple": "Púrpura real", "theme_sunset_orange": "Naranja atardecer", "opt_push": "Espacio superior (px)", "version_line": "{name} v{version}", "welcome_title": "{name} v{version}", "kofi_button": "☕ Ko-fi", "kofi_tooltip": "Apoya el desarrollo en Ko-fi", "patreon_button": "♥ Patreon", "rate_button": "👍 Valora este addon", "report_button": "Reportar un error", "welcome_close": "Cerrar", "welcome_body": "{name} añade una barra de progreso animada en la parte superior del repasador, mostrando cuánto llevas de tu sesión, con efectos de racha opcionales. Puedes cambiar el tema de color y otras opciones en cualquier momento desde Herramientas → Complementos → {name} → Config.", "welcome_support_note": "Este addon es gratuito y de código abierto (AGPLv3). Si te resulta útil, puedes apoyar su desarrollo abajo.",},
    "fr": {"streak": "{count} d'affilée", "opt_theme": "Thème de couleur", "opt_effects": "Effets de série (aura/or/texte)", "opt_save": "Accepter", "opt_cancel": "Annuler", "opt_defaults": "Restaurer les valeurs par défaut", "theme_classic_green": "Vert classique", "theme_fire_red": "Rouge feu", "theme_lagoon_turquoise": "Turquoise lagon", "theme_ocean_blue": "Bleu océan", "theme_rose_pink": "Rose poudré", "theme_royal_purple": "Violet royal", "theme_sunset_orange": "Orange coucher de soleil", "opt_push": "Espace en haut (px)", "version_line": "{name} v{version}", "welcome_title": "{name} v{version}", "kofi_button": "☕ Ko-fi", "kofi_tooltip": "Soutenir le développement sur Ko-fi", "patreon_button": "♥ Patreon", "rate_button": "👍 Noter ce module", "report_button": "Signaler un bug", "welcome_close": "Fermer", "welcome_body": "{name} ajoute une barre de progression animée en haut du réviseur, montrant votre avancement dans la session, avec des effets de série optionnels. Vous pouvez changer le thème de couleur et d'autres options à tout moment depuis Outils → Modules complémentaires → {name} → Config.", "welcome_support_note": "Ce module est gratuit et open source (AGPLv3). S'il vous est utile, vous pouvez soutenir son développement ci-dessous.",},
    "de": {"streak": "{count} in Folge", "opt_theme": "Farbschema", "opt_effects": "Serien-Effekte (Aura/Gold/Text)", "opt_save": "OK", "opt_cancel": "Abbrechen", "opt_defaults": "Standardwerte wiederherstellen", "theme_classic_green": "Klassisches Grün", "theme_fire_red": "Feuerrot", "theme_lagoon_turquoise": "Lagunentürkis", "theme_ocean_blue": "Ozeanblau", "theme_rose_pink": "Rosenrosa", "theme_royal_purple": "Königsviolett", "theme_sunset_orange": "Sonnenuntergangsorange", "opt_push": "Oberer Abstand (px)", "version_line": "{name} v{version}", "welcome_title": "{name} v{version}", "kofi_button": "☕ Ko-fi", "kofi_tooltip": "Entwicklung auf Ko-fi unterstützen", "patreon_button": "♥ Patreon", "rate_button": "👍 Add-on bewerten", "report_button": "Fehler melden", "welcome_close": "Schließen", "welcome_body": "{name} fügt oben im Reviewer eine animierte Fortschrittsleiste hinzu, die zeigt, wie weit du in deiner Sitzung bist, mit optionalen Serien-Effekten. Du kannst das Farbschema und weitere Optionen jederzeit unter Extras → Add-ons → {name} → Konfiguration ändern.", "welcome_support_note": "Dieses Add-on ist kostenlos und quelloffen (AGPLv3). Wenn es dir nützt, kannst du die Entwicklung unten unterstützen.",},
    "it": {"streak": "{count} di fila", "opt_theme": "Tema di colore", "opt_effects": "Effetti di serie (aura/oro/testo)", "opt_save": "Accetta", "opt_cancel": "Annulla", "opt_defaults": "Ripristina i valori predefiniti", "theme_classic_green": "Verde classico", "theme_fire_red": "Rosso fuoco", "theme_lagoon_turquoise": "Turchese laguna", "theme_ocean_blue": "Blu oceano", "theme_rose_pink": "Rosa antico", "theme_royal_purple": "Viola reale", "theme_sunset_orange": "Arancio tramonto", "opt_push": "Spazio superiore (px)", "version_line": "{name} v{version}", "welcome_title": "{name} v{version}", "kofi_button": "☕ Ko-fi", "kofi_tooltip": "Sostieni lo sviluppo su Ko-fi", "patreon_button": "♥ Patreon", "rate_button": "👍 Valuta questo componente", "report_button": "Segnala un bug", "welcome_close": "Chiudi", "welcome_body": "{name} aggiunge una barra di avanzamento animata in alto nel revisore, mostrando quanto sei avanti nella sessione, con effetti di serie opzionali. Puoi cambiare il tema colore e altre opzioni in qualsiasi momento da Strumenti → Componenti aggiuntivi → {name} → Configura.", "welcome_support_note": "Questo componente aggiuntivo è gratuito e open source (AGPLv3). Se ti è utile, puoi sostenerne lo sviluppo qui sotto.",},
    "pt_BR": {"streak": "{count} seguidas", "opt_theme": "Tema de cor", "opt_effects": "Efeitos de sequência (aura/ouro/texto)", "opt_save": "Aceitar", "opt_cancel": "Cancelar", "opt_defaults": "Restaurar os valores padrão", "theme_classic_green": "Verde clássico", "theme_fire_red": "Vermelho fogo", "theme_lagoon_turquoise": "Turquesa lagoa", "theme_ocean_blue": "Azul oceano", "theme_rose_pink": "Rosa suave", "theme_royal_purple": "Roxo real", "theme_sunset_orange": "Laranja pôr do sol", "opt_push": "Espaço no topo (px)", "version_line": "{name} v{version}", "welcome_title": "{name} v{version}", "kofi_button": "☕ Ko-fi", "kofi_tooltip": "Apoie o desenvolvimento no Ko-fi", "patreon_button": "♥ Patreon", "rate_button": "👍 Avalie este addon", "report_button": "Reportar um bug", "welcome_close": "Fechar", "welcome_body": "{name} adiciona uma barra de progresso animada no topo do revisor, mostrando o quanto você já avançou na sessão, com efeitos de sequência opcionais. Você pode mudar o tema de cor e outras opções a qualquer momento em Ferramentas → Complementos → {name} → Config.", "welcome_support_note": "Este addon é gratuito e de código aberto (AGPLv3). Se ele for útil para você, considere apoiar seu desenvolvimento abaixo.",},
    "pt_PT": {"streak": "{count} seguidas", "opt_theme": "Tema de cor", "opt_effects": "Efeitos de sequência (aura/ouro/texto)", "opt_save": "Aceitar", "opt_cancel": "Cancelar", "opt_defaults": "Restaurar os valores predefinidos", "theme_classic_green": "Verde clássico", "theme_fire_red": "Vermelho fogo", "theme_lagoon_turquoise": "Turquesa lagoa", "theme_ocean_blue": "Azul oceano", "theme_rose_pink": "Rosa suave", "theme_royal_purple": "Roxo real", "theme_sunset_orange": "Laranja pôr do sol", "opt_push": "Espaço no topo (px)", "version_line": "{name} v{version}", "welcome_title": "{name} v{version}", "kofi_button": "☕ Ko-fi", "kofi_tooltip": "Apoie o desenvolvimento no Ko-fi", "patreon_button": "♥ Patreon", "rate_button": "👍 Avalie este addon", "report_button": "Reportar um erro", "welcome_close": "Fechar", "welcome_body": "{name} adiciona uma barra de progresso animada no topo do revisor, mostrando quanto já avançou na sessão, com efeitos de sequência opcionais. Pode mudar o tema de cor e outras opções a qualquer momento em Ferramentas → Extras → {name} → Configuração.", "welcome_support_note": "Este addon é gratuito e de código aberto (AGPLv3). Se lhe for útil, pode apoiar o seu desenvolvimento abaixo.",},
    "nl": {"streak": "{count} op rij", "opt_theme": "Kleurthema", "opt_effects": "Reeks-effecten (aura/goud/tekst)", "opt_save": "Accepteren", "opt_cancel": "Annuleren", "opt_defaults": "Standaardwaarden herstellen", "theme_classic_green": "Klassiek groen", "theme_fire_red": "Vuurrood", "theme_lagoon_turquoise": "Lagoenturkoois", "theme_ocean_blue": "Oceaanblauw", "theme_rose_pink": "Rozenroze", "theme_royal_purple": "Koninklijk paars", "theme_sunset_orange": "Zonsondergang-oranje", "opt_push": "Ruimte bovenaan (px)"},
    "ca": {"streak": "{count} seguides", "opt_theme": "Tema de color", "opt_effects": "Efectes de ratxa (aura/or/text)", "opt_save": "Accepta", "opt_cancel": "Cancel·la", "opt_defaults": "Restaura els valors predeterminats", "theme_classic_green": "Verd clàssic", "theme_fire_red": "Vermell foc", "theme_lagoon_turquoise": "Turquesa llacuna", "theme_ocean_blue": "Blau oceà", "theme_rose_pink": "Rosa suau", "theme_royal_purple": "Porpra reial", "theme_sunset_orange": "Taronja capvespre", "opt_push": "Espai superior (px)"},
    "gl": {"streak": "{count} seguidas", "opt_theme": "Tema de cor", "opt_effects": "Efectos de racha (aura/ouro/texto)", "opt_save": "Aceptar", "opt_cancel": "Cancelar", "opt_defaults": "Restaurar os valores predeterminados", "theme_classic_green": "Verde clásico", "theme_fire_red": "Vermello lume", "theme_lagoon_turquoise": "Turquesa lagoa", "theme_ocean_blue": "Azul océano", "theme_rose_pink": "Rosa suave", "theme_royal_purple": "Púrpura real", "theme_sunset_orange": "Laranxa solpor", "opt_push": "Espazo superior (px)"},
    "ro": {"streak": "{count} la rând", "opt_theme": "Temă de culoare", "opt_effects": "Efecte de serie (aură/aur/text)", "opt_save": "Acceptă", "opt_cancel": "Anulează", "opt_defaults": "Restabilește valorile implicite", "theme_classic_green": "Verde clasic", "theme_fire_red": "Roșu foc", "theme_lagoon_turquoise": "Turcoaz lagună", "theme_ocean_blue": "Albastru ocean", "theme_rose_pink": "Roz trandafir", "theme_royal_purple": "Violet regal", "theme_sunset_orange": "Portocaliu apus", "opt_push": "Spațiu sus (px)"},
    "ru": {"streak": "{count} подряд", "opt_theme": "Цветовая тема", "opt_effects": "Эффекты серии (аура/золото/текст)", "opt_save": "Принять", "opt_cancel": "Отмена", "opt_defaults": "Восстановить значения по умолчанию", "theme_classic_green": "Классический зелёный", "theme_fire_red": "Огненно-красный", "theme_lagoon_turquoise": "Бирюза лагуны", "theme_ocean_blue": "Океанский синий", "theme_rose_pink": "Розовый", "theme_royal_purple": "Королевский фиолетовый", "theme_sunset_orange": "Оранжевый закат", "opt_push": "Отступ сверху (px)"},
    "uk": {"streak": "{count} поспіль", "opt_theme": "Кольорова тема", "opt_effects": "Ефекти серії (аура/золото/текст)", "opt_save": "Прийняти", "opt_cancel": "Скасувати", "opt_defaults": "Відновити типові значення", "theme_classic_green": "Класичний зелений", "theme_fire_red": "Вогняний червоний", "theme_lagoon_turquoise": "Бірюза лагуни", "theme_ocean_blue": "Океанський синій", "theme_rose_pink": "Рожевий", "theme_royal_purple": "Королівський фіолетовий", "theme_sunset_orange": "Помаранчевий захід", "opt_push": "Відступ зверху (px)"},
    "pl": {"streak": "{count} z rzędu", "opt_theme": "Motyw kolorów", "opt_effects": "Efekty serii (aura/złoto/tekst)", "opt_save": "Akceptuj", "opt_cancel": "Anuluj", "opt_defaults": "Przywróć wartości domyślne", "theme_classic_green": "Klasyczna zieleń", "theme_fire_red": "Ognista czerwień", "theme_lagoon_turquoise": "Turkus laguny", "theme_ocean_blue": "Oceaniczny błękit", "theme_rose_pink": "Różany", "theme_royal_purple": "Królewski fiolet", "theme_sunset_orange": "Pomarańcz zachodu", "opt_push": "Odstęp u góry (px)"},
    "cs": {"streak": "{count} v řadě", "opt_theme": "Barevné téma", "opt_effects": "Efekty série (aura/zlato/text)", "opt_save": "Přijmout", "opt_cancel": "Zrušit", "opt_defaults": "Obnovit výchozí hodnoty", "theme_classic_green": "Klasická zelená", "theme_fire_red": "Ohnivě červená", "theme_lagoon_turquoise": "Lagunová tyrkysová", "theme_ocean_blue": "Oceánská modrá", "theme_rose_pink": "Růžová", "theme_royal_purple": "Královská fialová", "theme_sunset_orange": "Oranžová západu slunce", "opt_push": "Horní mezera (px)"},
    "sk": {"streak": "{count} v rade", "opt_theme": "Farebná téma", "opt_effects": "Efekty série (aura/zlato/text)", "opt_save": "Prijať", "opt_cancel": "Zrušiť", "opt_defaults": "Obnoviť predvolené hodnoty", "theme_classic_green": "Klasická zelená", "theme_fire_red": "Ohnivo červená", "theme_lagoon_turquoise": "Lagúnová tyrkysová", "theme_ocean_blue": "Oceánska modrá", "theme_rose_pink": "Ružová", "theme_royal_purple": "Kráľovská fialová", "theme_sunset_orange": "Oranžová západu slnka", "opt_push": "Horná medzera (px)"},
    "sl": {"streak": "{count} zapored", "opt_theme": "Barvna tema", "opt_effects": "Učinki niza (avra/zlato/besedilo)", "opt_save": "Sprejmi", "opt_cancel": "Prekliči", "opt_defaults": "Obnovi privzete vrednosti", "theme_classic_green": "Klasična zelena", "theme_fire_red": "Ognjeno rdeča", "theme_lagoon_turquoise": "Turkizna lagune", "theme_ocean_blue": "Oceansko modra", "theme_rose_pink": "Rožnata", "theme_royal_purple": "Kraljevsko vijolična", "theme_sunset_orange": "Oranžna sončnega zahoda", "opt_push": "Zgornji razmik (px)"},
    "hr": {"streak": "{count} zaredom", "opt_theme": "Tema boje", "opt_effects": "Efekti niza (aura/zlato/tekst)", "opt_save": "Prihvati", "opt_cancel": "Odustani", "opt_defaults": "Vrati zadane vrijednosti", "theme_classic_green": "Klasična zelena", "theme_fire_red": "Vatreno crvena", "theme_lagoon_turquoise": "Tirkizna lagune", "theme_ocean_blue": "Oceanski plava", "theme_rose_pink": "Ružičasta", "theme_royal_purple": "Kraljevski ljubičasta", "theme_sunset_orange": "Naranča zalaska", "opt_push": "Gornji razmak (px)"},
    "sr": {"streak": "{count} заредом", "opt_theme": "Тема боје", "opt_effects": "Ефекти низа (аура/злато/текст)", "opt_save": "Прихвати", "opt_cancel": "Откажи", "opt_defaults": "Врати подразумеване вредности", "theme_classic_green": "Класична зелена", "theme_fire_red": "Ватрено црвена", "theme_lagoon_turquoise": "Тиркизна лагуне", "theme_ocean_blue": "Океанско плава", "theme_rose_pink": "Ружичаста", "theme_royal_purple": "Краљевски љубичаста", "theme_sunset_orange": "Наранџаста заласка", "opt_push": "Горњи размак (px)"},
    "bg": {"streak": "{count} поредни", "opt_theme": "Цветова тема", "opt_effects": "Ефекти на серия (аура/злато/текст)", "opt_save": "Приеми", "opt_cancel": "Отказ", "opt_defaults": "Възстанови стойностите по подразбиране", "theme_classic_green": "Класично зелено", "theme_fire_red": "Огнено червено", "theme_lagoon_turquoise": "Тюркоаз лагуна", "theme_ocean_blue": "Океанско синьо", "theme_rose_pink": "Розово", "theme_royal_purple": "Кралско лилаво", "theme_sunset_orange": "Оранжево на залез", "opt_push": "Горно отстояние (px)"},
    "sv": {"streak": "{count} i rad", "opt_theme": "Färgtema", "opt_effects": "Serie-effekter (aura/guld/text)", "opt_save": "Acceptera", "opt_cancel": "Avbryt", "opt_defaults": "Återställ standardvärden", "theme_classic_green": "Klassiskt grönt", "theme_fire_red": "Eldrött", "theme_lagoon_turquoise": "Lagunturkos", "theme_ocean_blue": "Havsblått", "theme_rose_pink": "Rosenrosa", "theme_royal_purple": "Kungligt lila", "theme_sunset_orange": "Solnedgångsorange", "opt_push": "Utrymme upptill (px)"},
    "da": {"streak": "{count} i træk", "opt_theme": "Farvetema", "opt_effects": "Stime-effekter (aura/guld/tekst)", "opt_save": "Accepter", "opt_cancel": "Annuller", "opt_defaults": "Gendan standardværdier", "theme_classic_green": "Klassisk grøn", "theme_fire_red": "Ildrød", "theme_lagoon_turquoise": "Lagune-turkis", "theme_ocean_blue": "Havblå", "theme_rose_pink": "Rosenrød", "theme_royal_purple": "Kongelig lilla", "theme_sunset_orange": "Solnedgangsorange", "opt_push": "Plads foroven (px)"},
    "nb": {"streak": "{count} på rad", "opt_theme": "Fargetema", "opt_effects": "Rekke-effekter (aura/gull/tekst)", "opt_save": "Godta", "opt_cancel": "Avbryt", "opt_defaults": "Gjenopprett standardverdier", "theme_classic_green": "Klassisk grønn", "theme_fire_red": "Ildrød", "theme_lagoon_turquoise": "Lagune-turkis", "theme_ocean_blue": "Havblå", "theme_rose_pink": "Rosenrosa", "theme_royal_purple": "Kongelig lilla", "theme_sunset_orange": "Solnedgangsoransje", "opt_push": "Plass øverst (px)"},
    "fi": {"streak": "{count} putkeen", "opt_theme": "Väriteema", "opt_effects": "Putki-tehosteet (aura/kulta/teksti)", "opt_save": "Hyväksy", "opt_cancel": "Peruuta", "opt_defaults": "Palauta oletusarvot", "theme_classic_green": "Klassinen vihreä", "theme_fire_red": "Tulipunainen", "theme_lagoon_turquoise": "Laguunin turkoosi", "theme_ocean_blue": "Merensininen", "theme_rose_pink": "Ruusunpunainen", "theme_royal_purple": "Kuninkaallinen violetti", "theme_sunset_orange": "Auringonlaskun oranssi", "opt_push": "Ylätila (px)"},
    "et": {"streak": "{count} järjest", "opt_theme": "Värviteema", "opt_effects": "Seeria efektid (aura/kuld/tekst)", "opt_save": "Nõustu", "opt_cancel": "Tühista", "opt_defaults": "Taasta vaikeväärtused", "theme_classic_green": "Klassikaline roheline", "theme_fire_red": "Tulipunane", "theme_lagoon_turquoise": "Laguuni türkiis", "theme_ocean_blue": "Ookeanisinine", "theme_rose_pink": "Roosa", "theme_royal_purple": "Kuninglik lilla", "theme_sunset_orange": "Loojangu oranž", "opt_push": "Ülemine ruum (px)"},
    "lt": {"streak": "{count} iš eilės", "opt_theme": "Spalvų tema", "opt_effects": "Serijos efektai (aura/auksas/tekstas)", "opt_save": "Priimti", "opt_cancel": "Atšaukti", "opt_defaults": "Atkurti numatytąsias reikšmes", "theme_classic_green": "Klasikinė žalia", "theme_fire_red": "Ugnies raudona", "theme_lagoon_turquoise": "Lagūnos turkis", "theme_ocean_blue": "Vandenyno mėlyna", "theme_rose_pink": "Rožinė", "theme_royal_purple": "Karališka violetinė", "theme_sunset_orange": "Saulėlydžio oranžinė", "opt_push": "Viršutinis tarpas (px)"},
    "hu": {"streak": "{count} egymás után", "opt_theme": "Színtéma", "opt_effects": "Sorozat-effektek (aura/arany/szöveg)", "opt_save": "Elfogadás", "opt_cancel": "Mégse", "opt_defaults": "Alapértelmezett értékek visszaállítása", "theme_classic_green": "Klasszikus zöld", "theme_fire_red": "Tűzpiros", "theme_lagoon_turquoise": "Lagúna türkiz", "theme_ocean_blue": "Óceánkék", "theme_rose_pink": "Rózsaszín", "theme_royal_purple": "Királyi lila", "theme_sunset_orange": "Naplemente narancs", "opt_push": "Felső térköz (px)"},
    "el": {"streak": "{count} στη σειρά", "opt_theme": "Θέμα χρώματος", "opt_effects": "Εφέ σερί (άουρα/χρυσό/κείμενο)", "opt_save": "Αποδοχή", "opt_cancel": "Ακύρωση", "opt_defaults": "Επαναφορά προεπιλογών", "theme_classic_green": "Κλασικό πράσινο", "theme_fire_red": "Κόκκινο φωτιάς", "theme_lagoon_turquoise": "Τιρκουάζ λιμνοθάλασσας", "theme_ocean_blue": "Μπλε ωκεανού", "theme_rose_pink": "Ροζ τριαντάφυλλο", "theme_royal_purple": "Βασιλικό μωβ", "theme_sunset_orange": "Πορτοκαλί ηλιοβασιλέματος", "opt_push": "Άνω κενό (px)"},
    "tr": {"streak": "{count} üst üste", "opt_theme": "Renk teması", "opt_effects": "Seri efektleri (aura/altın/metin)", "opt_save": "Kabul Et", "opt_cancel": "İptal", "opt_defaults": "Varsayılan değerleri geri yükle", "theme_classic_green": "Klasik yeşil", "theme_fire_red": "Ateş kırmızısı", "theme_lagoon_turquoise": "Lagün turkuazı", "theme_ocean_blue": "Okyanus mavisi", "theme_rose_pink": "Gül pembesi", "theme_royal_purple": "Kraliyet moru", "theme_sunset_orange": "Gün batımı turuncusu", "opt_push": "Üst boşluk (px)"},
    "ar": {"streak": "{count} متتالية", "opt_theme": "سمة اللون", "opt_effects": "تأثيرات السلسلة (هالة/ذهب/نص)", "opt_save": "قبول", "opt_cancel": "إلغاء", "opt_defaults": "استعادة القيم الافتراضية", "theme_classic_green": "أخضر كلاسيكي", "theme_fire_red": "أحمر ناري", "theme_lagoon_turquoise": "فيروزي البحيرة", "theme_ocean_blue": "أزرق محيطي", "theme_rose_pink": "وردي زهري", "theme_royal_purple": "أرجواني ملكي", "theme_sunset_orange": "برتقالي الغروب", "opt_push": "مسافة علوية (px)"},
    "he": {"streak": "{count} ברצף", "opt_theme": "ערכת צבע", "opt_effects": "אפקטי רצף (הילה/זהב/טקסט)", "opt_save": "אישור", "opt_cancel": "ביטול", "opt_defaults": "שחזור ברירות המחדל", "theme_classic_green": "ירוק קלאסי", "theme_fire_red": "אדום אש", "theme_lagoon_turquoise": "טורקיז לגונה", "theme_ocean_blue": "כחול אוקיינוס", "theme_rose_pink": "ורוד ורד", "theme_royal_purple": "סגול מלכותי", "theme_sunset_orange": "כתום שקיעה", "opt_push": "מרווח עליון (px)"},
    "fa": {"streak": "{count} پیاپی", "opt_theme": "زمینه رنگ", "opt_effects": "جلوه‌های زنجیره (هاله/طلا/متن)", "opt_save": "تأیید", "opt_cancel": "لغو", "opt_defaults": "بازگرداندن مقادیر پیش‌فرض", "theme_classic_green": "سبز کلاسیک", "theme_fire_red": "قرمز آتشین", "theme_lagoon_turquoise": "فیروزهٔ تالاب", "theme_ocean_blue": "آبی اقیانوسی", "theme_rose_pink": "صورتی گلی", "theme_royal_purple": "بنفش سلطنتی", "theme_sunset_orange": "نارنجی غروب", "opt_push": "فاصله بالا (px)"},
    "hi": {"streak": "{count} लगातार", "opt_theme": "रंग थीम", "opt_effects": "श्रृंखला प्रभाव (आभा/सोना/पाठ)", "opt_save": "स्वीकार करें", "opt_cancel": "रद्द करें", "opt_defaults": "डिफ़ॉल्ट मान पुनर्स्थापित करें", "theme_classic_green": "क्लासिक हरा", "theme_fire_red": "आग जैसा लाल", "theme_lagoon_turquoise": "लैगून फिरोज़ी", "theme_ocean_blue": "समुद्री नीला", "theme_rose_pink": "हल्का गुलाबी", "theme_royal_purple": "शाही बैंगनी", "theme_sunset_orange": "सूर्यास्त नारंगी", "opt_push": "ऊपरी स्थान (px)"},
    "th": {"streak": "{count} ครั้งติดต่อกัน", "opt_theme": "ธีมสี", "opt_effects": "เอฟเฟกต์สตรีค (ออร่า/ทอง/ข้อความ)", "opt_save": "ยอมรับ", "opt_cancel": "ยกเลิก", "opt_defaults": "คืนค่าเริ่มต้น", "theme_classic_green": "เขียวคลาสสิก", "theme_fire_red": "แดงเพลิง", "theme_lagoon_turquoise": "เทอร์ควอยซ์ทะเลสาบ", "theme_ocean_blue": "น้ำเงินมหาสมุทร", "theme_rose_pink": "ชมพูกุหลาบ", "theme_royal_purple": "ม่วงราชวงศ์", "theme_sunset_orange": "ส้มอาทิตย์อัสดง", "opt_push": "ระยะห่างด้านบน (px)"},
    "vi": {"streak": "{count} liên tiếp", "opt_theme": "Chủ đề màu", "opt_effects": "Hiệu ứng chuỗi (hào quang/vàng/văn bản)", "opt_save": "Chấp nhận", "opt_cancel": "Hủy", "opt_defaults": "Khôi phục giá trị mặc định", "theme_classic_green": "Xanh lá cổ điển", "theme_fire_red": "Đỏ lửa", "theme_lagoon_turquoise": "Ngọc lam đầm phá", "theme_ocean_blue": "Xanh đại dương", "theme_rose_pink": "Hồng phấn", "theme_royal_purple": "Tím hoàng gia", "theme_sunset_orange": "Cam hoàng hôn", "opt_push": "Khoảng cách trên (px)"},
    "id": {"streak": "{count} berturut-turut", "opt_theme": "Tema warna", "opt_effects": "Efek rentetan (aura/emas/teks)", "opt_save": "Terima", "opt_cancel": "Batal", "opt_defaults": "Pulihkan nilai bawaan", "theme_classic_green": "Hijau klasik", "theme_fire_red": "Merah api", "theme_lagoon_turquoise": "Toska laguna", "theme_ocean_blue": "Biru samudra", "theme_rose_pink": "Merah muda lembut", "theme_royal_purple": "Ungu kerajaan", "theme_sunset_orange": "Jingga senja", "opt_push": "Jarak atas (px)"},
    "ms": {"streak": "{count} berturut-turut", "opt_theme": "Tema warna", "opt_effects": "Kesan rentetan (aura/emas/teks)", "opt_save": "Terima", "opt_cancel": "Batal", "opt_defaults": "Pulihkan nilai lalai", "theme_classic_green": "Hijau klasik", "theme_fire_red": "Merah api", "theme_lagoon_turquoise": "Pirus lagun", "theme_ocean_blue": "Biru lautan", "theme_rose_pink": "Merah jambu", "theme_royal_purple": "Ungu diraja", "theme_sunset_orange": "Jingga senja", "opt_push": "Jarak atas (px)"},
    "ja": {"streak": "{count}回連続", "opt_theme": "カラーテーマ", "opt_effects": "連続エフェクト(オーラ/金色/テキスト)", "opt_save": "OK", "opt_cancel": "キャンセル", "opt_defaults": "既定値に戻す", "theme_classic_green": "クラシックグリーン", "theme_fire_red": "ファイアレッド", "theme_lagoon_turquoise": "ラグーンターコイズ", "theme_ocean_blue": "オーシャンブルー", "theme_rose_pink": "ローズピンク", "theme_royal_purple": "ロイヤルパープル", "theme_sunset_orange": "サンセットオレンジ", "opt_push": "上部の余白 (px)"},
    "ko": {"streak": "{count}회 연속", "opt_theme": "색상 테마", "opt_effects": "연속 효과 (오라/골드/텍스트)", "opt_save": "확인", "opt_cancel": "취소", "opt_defaults": "기본값 복원", "theme_classic_green": "클래식 그린", "theme_fire_red": "파이어 레드", "theme_lagoon_turquoise": "라군 터콰이즈", "theme_ocean_blue": "오션 블루", "theme_rose_pink": "로즈 핑크", "theme_royal_purple": "로열 퍼플", "theme_sunset_orange": "선셋 오렌지", "opt_push": "상단 여백 (px)"},
    "zh_CN": {"streak": "连续{count}次", "opt_theme": "配色主题", "opt_effects": "连击特效（光环/金色/文字）", "opt_save": "确定", "opt_cancel": "取消", "opt_defaults": "恢复默认值", "theme_classic_green": "经典绿", "theme_fire_red": "烈焰红", "theme_lagoon_turquoise": "泻湖绿松石", "theme_ocean_blue": "海洋蓝", "theme_rose_pink": "玫瑰粉", "theme_royal_purple": "皇家紫", "theme_sunset_orange": "落日橙", "opt_push": "顶部间距 (px)"},
    "zh_TW": {"streak": "連續{count}次", "opt_theme": "配色主題", "opt_effects": "連擊特效（光環/金色/文字）", "opt_save": "確定", "opt_cancel": "取消", "opt_defaults": "還原預設值", "theme_classic_green": "經典綠", "theme_fire_red": "烈焰紅", "theme_lagoon_turquoise": "潟湖綠松石", "theme_ocean_blue": "海洋藍", "theme_rose_pink": "玫瑰粉", "theme_royal_purple": "皇家紫", "theme_sunset_orange": "落日橙", "opt_push": "頂部間距 (px)"},
    "eo": {"streak": "{count} sinsekve", "opt_theme": "Kolora etoso", "opt_effects": "Seri-efektoj (aŭro/oro/teksto)", "opt_save": "Akcepti", "opt_cancel": "Nuligi", "opt_defaults": "Restarigi defaŭltajn valorojn", "theme_classic_green": "Klasika verda", "theme_fire_red": "Fajra ruĝa", "theme_lagoon_turquoise": "Laguna turkiso", "theme_ocean_blue": "Oceana blua", "theme_rose_pink": "Roza rozkolora", "theme_royal_purple": "Reĝa purpura", "theme_sunset_orange": "Sunsubira oranĝa", "opt_push": "Supra spaco (px)"},
    "af": {"streak": "{count} agtereen", "opt_theme": "Kleurtema", "opt_effects": "Reeks-effekte (aura/goud/teks)", "opt_save": "Aanvaar", "opt_cancel": "Kanselleer", "opt_defaults": "Herstel verstekwaardes", "theme_classic_green": "Klassieke groen", "theme_fire_red": "Vuurrooi", "theme_lagoon_turquoise": "Laguneturkoois", "theme_ocean_blue": "Oseaanblou", "theme_rose_pink": "Roosroos", "theme_royal_purple": "Koninklike pers", "theme_sunset_orange": "Sonsondergang-oranje", "opt_push": "Boonste spasie (px)"},
    "be": {"streak": "{count} запар", "opt_theme": "Каляровая тэма", "opt_effects": "Эфекты серыі (аура/золата/тэкст)", "opt_save": "Прыняць", "opt_cancel": "Адмяніць", "opt_defaults": "Аднавіць прадвызначаныя значэнні", "theme_classic_green": "Класічны зялёны", "theme_fire_red": "Вогненна-чырвоны", "theme_lagoon_turquoise": "Бірюза лагуны", "theme_ocean_blue": "Акіянскі блакітны", "theme_rose_pink": "Ружовы", "theme_royal_purple": "Каралеўскі фіялетавы", "theme_sunset_orange": "Аранжавы захад сонца", "opt_push": "Верхні водступ (px)"},
    "eu": {"streak": "{count} jarraian", "opt_theme": "Kolore-gaia", "opt_effects": "Mugako efektuak (aura/urrea/testua)", "opt_save": "Onartu", "opt_cancel": "Utzi", "opt_defaults": "Leheneratu balio lehenetsiak", "theme_classic_green": "Berde klasikoa", "theme_fire_red": "Su gorria", "theme_lagoon_turquoise": "Aintzira turkesa", "theme_ocean_blue": "Ozeano urdina", "theme_rose_pink": "Arrosa leuna", "theme_royal_purple": "More erregalea", "theme_sunset_orange": "Iluntziko laranja", "opt_push": "Goiko tartea (px)"},
    "ga": {"streak": "{count} as a chéile", "opt_theme": "Téama dathanna", "opt_effects": "Éifeachtaí sraithe (aura/ór/téacs)", "opt_save": "Glac leis", "opt_cancel": "Cealaigh", "opt_defaults": "Athchóirigh na réamhshocruithe", "theme_classic_green": "Glas clasaiceach", "theme_fire_red": "Dearg tine", "theme_lagoon_turquoise": "Turcaidhe murlaigh", "theme_ocean_blue": "Gorm aigéin", "theme_rose_pink": "Bándearg rósach", "theme_royal_purple": "Corcra ríoga", "theme_sunset_orange": "Oráiste luí gréine", "opt_push": "Spás barr (px)"},
    "hy": {"streak": "{count} անընդմեջ", "opt_theme": "Գույնի թեմա", "opt_effects": "Շարքի էֆֆեկտներ (աուրա/ոսկի/տեքստ)", "opt_save": "Ընդունել", "opt_cancel": "Չեղարկել", "opt_defaults": "Վերականգնել լռելյայն արժեքները", "theme_classic_green": "Դասական կանաչ", "theme_fire_red": "Կրակի կարմիր", "theme_lagoon_turquoise": "Ծովածոցի փիրուզ", "theme_ocean_blue": "Օվկիանոսային կապույտ", "theme_rose_pink": "Վարդագույն", "theme_royal_purple": "Արքայական մանուշակ", "theme_sunset_orange": "Մայրամուտի նարնջագույն", "opt_push": "Վերին բացատ (px)"},
    "jbo": {"streak": "{count} ralterba'u", "opt_theme": "skari tarmi", "opt_effects": "seltcu ca'a (aura/solji/tcita)", "opt_save": "cpacu", "opt_cancel": "sisti", "opt_defaults": "xruti fi le krasi", "theme_classic_green": "farlu crino", "theme_fire_red": "fagri xunre", "theme_lagoon_turquoise": "cicna blanu", "theme_ocean_blue": "braxamsi blanu", "theme_rose_pink": "xunblabi", "theme_royal_purple": "noltru zirpu", "theme_sunset_orange": "solri nicte pelxu", "opt_push": "gapru canlu (px)"},
    "la": {"streak": "{count} continuo", "opt_theme": "Thema coloris", "opt_effects": "Effectus seriei (aura/aurum/textus)", "opt_save": "Accipe", "opt_cancel": "Cancella", "opt_defaults": "Valores primos restituere", "theme_classic_green": "Viride classicum", "theme_fire_red": "Rubrum igneum", "theme_lagoon_turquoise": "Turcinus lacunae", "theme_ocean_blue": "Caeruleum oceanicum", "theme_rose_pink": "Roseus rosaceus", "theme_royal_purple": "Purpura regia", "theme_sunset_orange": "Aurantium solis occasus", "opt_push": "Spatium superius (px)"},
    "lv": {"streak": "{count} pēc kārtas", "opt_theme": "Krāsu tēma", "opt_effects": "Sērijas efekti (aura/zelts/teksts)", "opt_save": "Pieņemt", "opt_cancel": "Atcelt", "opt_defaults": "Atjaunot noklusējuma vērtības", "theme_classic_green": "Klasiskā zaļā", "theme_fire_red": "Uguns sarkanā", "theme_lagoon_turquoise": "Lagūnas tirkīzs", "theme_ocean_blue": "Okeāna zilā", "theme_rose_pink": "Rožu rozā", "theme_royal_purple": "Karaliskā violetā", "theme_sunset_orange": "Saulrieta oranžā", "opt_push": "Augšējā atstarpe (px)"},
    "mn": {"streak": "{count} дараалсан", "opt_theme": "Өнгөний сэдэв", "opt_effects": "Дараалсан эффект (аура/алт/текст)", "opt_save": "Зөвшөөрөх", "opt_cancel": "Цуцлах", "opt_defaults": "Анхны утгыг сэргээх", "theme_classic_green": "Сонгодог ногоон", "theme_fire_red": "Гал улаан", "theme_lagoon_turquoise": "Нуурын оюу", "theme_ocean_blue": "Далайн цэнхэр", "theme_rose_pink": "Сарнайн ягаан", "theme_royal_purple": "Хаант ягаан", "theme_sunset_orange": "Нарны жаргалтын улбар шар", "opt_push": "Дээд зай (px)"},
    "my": {"streak": "{count} ကြိမ်ဆက်တိုက်", "opt_theme": "အရောင်အပြင်အဆင်", "opt_effects": "ဆက်တိုက် ကြောင်းဆက်တုံ့ပြန်မှုများ (အောရာ/ရွှေရောင်/စာသား)", "opt_save": "လက်ခံပါ", "opt_cancel": "မလုပ်တော့ပါ", "opt_defaults": "မူလတန်ဖိုးများ ပြန်လည်ရယူပါ", "theme_classic_green": "ခေတ်ဟောင်းစိမ်း", "theme_fire_red": "မီးနီ", "theme_lagoon_turquoise": "လဂွန်း ကျောက်စိမ်းရောင်", "theme_ocean_blue": "သမုဒ္ဒရာပြာ", "theme_rose_pink": "နှင်းဆီပန်းရောင်", "theme_royal_purple": "နန်းတွင်းခရမ်း", "theme_sunset_orange": "နေဝင်ချိန် လိမ္မော်ရောင်", "opt_push": "ထိပ်ဆုံး နေရာ (px)"},
    "oc": {"streak": "{count} d'afila", "opt_theme": "Tèma de color", "opt_effects": "Efièches de seria (aura/aur/tèxte)", "opt_save": "Acceptar", "opt_cancel": "Anullar", "opt_defaults": "Restablir las valors per defaut", "theme_classic_green": "Verd classic", "theme_fire_red": "Roge de fòc", "theme_lagoon_turquoise": "Turquesa laguna", "theme_ocean_blue": "Blau ocean", "theme_rose_pink": "Ròsa doça", "theme_royal_purple": "Porpre reiau", "theme_sunset_orange": "Aurenga de solcelh", "opt_push": "Espaci superior (px)"},
    "sq": {"streak": "{count} radhazi", "opt_theme": "Tema e ngjyrës", "opt_effects": "Efekte të serisë (aureolë/ar/tekst)", "opt_save": "Prano", "opt_cancel": "Anulo", "opt_defaults": "Rikthe vlerat e parazgjedhura", "theme_classic_green": "Gjelbër klasik", "theme_fire_red": "Kuq zjarri", "theme_lagoon_turquoise": "Firuzi i lagunës", "theme_ocean_blue": "Blu oqeani", "theme_rose_pink": "Rozë trëndafili", "theme_royal_purple": "Vjollcë mbretëror", "theme_sunset_orange": "Portokalli perëndimi", "opt_push": "Hapësira e sipërme (px)"},
    "ug": {"streak": "{count} قېتىم ئارقىمۇ-ئارقا", "opt_theme": "رەڭ تېمىسى", "opt_effects": "سىلسىلە تەسىراتلىرى (ھالە/ئالتۇن/تېكىست)", "opt_save": "قوبۇل قىلىش", "opt_cancel": "ۋاز كەچمەك", "opt_defaults": "كۆڭۈلدىكى قىممەتلەرنى ئەسلىگە كەلتۈرۈش", "theme_classic_green": "كلاسسىك يېشىل", "theme_fire_red": "ئوت قىزىل", "theme_lagoon_turquoise": "لاگۇنا كۆكۈچ", "theme_ocean_blue": "ئوكيان كۆك", "theme_rose_pink": "ئەتىرگۈل ھالرەڭ", "theme_royal_purple": "ھەشەمەتلىك بىنەپشە", "theme_sunset_orange": "كۈن ئېتىشىنىڭ سېرىق-قىزىلى", "opt_push": "ئۈستى بوشلۇق (px)"},
    "uz": {"streak": "{count} ta ketma-ket", "opt_theme": "Rang mavzusi", "opt_effects": "Ketma-ketlik effektlari (aura/oltin/matn)", "opt_save": "Qabul qilish", "opt_cancel": "Bekor qilish", "opt_defaults": "Standart qiymatlarni tiklash", "theme_classic_green": "Klassik yashil", "theme_fire_red": "Olov qizil", "theme_lagoon_turquoise": "Lagun feruzasi", "theme_ocean_blue": "Okean ko'k", "theme_rose_pink": "Atirgul pushti", "theme_royal_purple": "Qirollik binafsha", "theme_sunset_orange": "Quyosh botishi to'q sariq", "opt_push": "Yuqori bo'shliq (px)"},
    "fil": {"streak": "{count} sunod-sunod", "opt_theme": "Tema ng kulay", "opt_effects": "Mga epekto ng streak (aura/ginto/teksto)", "opt_save": "Tanggapin", "opt_cancel": "Kanselahin", "opt_defaults": "Ibalik ang mga default na halaga", "theme_classic_green": "Klasikong berde", "theme_fire_red": "Pulang apoy", "theme_lagoon_turquoise": "Turkesang Lagoon", "theme_ocean_blue": "Asul na karagatan", "theme_rose_pink": "Rosas na Pink", "theme_royal_purple": "Maharlikang lila", "theme_sunset_orange": "Kahel ng paglubog", "opt_push": "Puwang sa itaas (px)"},
}

COMPLETE_LOCALES: frozenset[str] = frozenset(TRANSLATIONS)


def _log(exc: Exception) -> None:
    print(f"[coreprogress] {exc!r}")


def _resolve(code: str) -> str:
    code = code.replace("-", "_")
    parts = code.split("_")
    primary = parts[0].lower()
    region = parts[1].upper() if len(parts) > 1 else ""
    if primary == "zh":
        return "zh_TW" if region in ("TW", "HK", "MO") or "HANT" in code.upper() else "zh_CN"
    if primary == "pt":
        return "pt_PT" if region == "PT" else "pt_BR"
    if primary in ("fil", "tl"):
        return "fil"
    return primary if primary in TRANSLATIONS else FALLBACK


@lru_cache(maxsize=1)
def current_lang() -> str:
    try:
        import anki.lang

        raw = (
            getattr(anki.lang, "current_lang", None)
            or getattr(anki.lang, "currentLang", None)
            or ""
        )
        code = raw if isinstance(raw, str) else ""
        return _resolve(code)
    except Exception as exc:
        _log(exc)
        return FALLBACK


def t(key: str) -> str:
    table = TRANSLATIONS.get(current_lang(), TRANSLATIONS[FALLBACK])
    value = table.get(key)
    if value is not None:
        return value
    return TRANSLATIONS[FALLBACK].get(key, key)


def streak_label(streak: int) -> str:
    if not is_celebration_milestone(streak):
        return ""
    return t("streak").format(count=streak)